prjPROJECT/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using prjPROJECT.Models; // Web 應用程式的表單驗證服務需引用此類別

namespace prjPROJECT.Controllers
{
    // [Authorize]屬性確保此控制器中的所有方法都要求用戶已經登入才能訪問
    [Authorize]
    public class MemberController : Controller
    {
        // 建立與資料庫的連線實例
        public dbDATABASEEntities db = new dbDATABASEEntities();

        // Get: Member/Index
        [HttpGet]
        public ActionResult Index()
        {
            return View("../Home/Index", "_LayoutMember");
        }


        // Get: Member/Logout
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut(); // 登出
            return RedirectToAction("Login", "Home");
        }


        // Get: Member/Account
        public ActionResult Account()
        {
            //取得登入會員的帳號並指定給 fUserID
            string fUserID = User.Identity.Name;
            var UserName = db.tMember
                .Where(m => m.fMem_UserID == fUserID)
                .ToList();
            return View(UserName);
        }


        // Get: Member/HomePage
        public ActionResult HomePage()
        {

            return View();
        }
    }
}

prjPROJECT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - YU</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">YU</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="@Url.Action("Index", "Home")">
                            簡介
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("註冊", "Register", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("登入", "Login", "Home", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - YU</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>

prjPROJECT/Views/Shared/_LayoutMember.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - YU</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">YU</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        @Html.ActionLink("首頁", "HomePage", "Member", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("帳戶", "Account", "Member", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("登出", "Logout", "Member", null, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - YU</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>